# Generated by Django 4.2.7 on 2023-12-09 10:42

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_Information',
            fields=[
                ('roomId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pro', models.IntegerField(default=0)),
                ('con', models.IntegerField(default=0)),
                ('topic', models.CharField(max_length=200)),
                ('period', models.IntegerField(default=7)),
            ],
        ),
    ]
