# Generated by Django 4.2.7 on 2023-12-09 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_information'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room_Information',
            new_name='RoomInformation',
        ),
    ]
