# Generated by Django 4.2.7 on 2023-12-12 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vote_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='created_at',
        ),
    ]
