# Generated by Django 4.2.7 on 2023-12-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_room_information_roominformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roominformation',
            old_name='con',
            new_name='cons',
        ),
        migrations.RenameField(
            model_name='roominformation',
            old_name='pro',
            new_name='pros',
        ),
        migrations.AddField(
            model_name='roominformation',
            name='replies',
            field=models.IntegerField(default=0),
        ),
    ]
