# Generated by Django 4.2.7 on 2023-12-12 00:56

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_vote_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='kakao_id',
            field=models.CharField(default='탈퇴한유저', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='kakao_id',
            field=models.ForeignKey(on_delete=models.SET(api.models.get_default_user), related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPro', models.BooleanField()),
                ('nickname', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kakao_id', models.ForeignKey(on_delete=models.SET(api.models.get_default_user), related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.roominformation')),
            ],
        ),
    ]
