# Generated by Django 4.2.7 on 2023-12-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customuser_kakao_id_alter_vote_kakao_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.CharField(default='', max_length=255),
        ),
    ]
